### ISSUE TITLE
[API] Put all dashboard-related data in one endpoint

### ISSUE THREAD

**Issue by Songkeys** [GRP-17/feedback-backend#13]
It's not good to request multiple times for different data wanted in dashboard.

Let's make a new api that allows us make it one go.

Example:

```
/dashboard
```

To specify things we want, pass array via query string:

```
/dashboard?endpoints[]=feedback&endpoints[]=feedback_rating_count&....
```

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR5: Dashboard: feedback received](https://trello.com/c/eQhIvSv5/20-spr5-dashboard-feedback-received)

**Comment by benorourke** [comment]
https://feedback-analysis-grp-app.herokuapp.com/dashboard/feedback,feedback_count,feedback_rating_average,feedback_rating_count,feedback_sentiment_count

Added the dashboard endpoint with (optional) endpoints to be specified. This will save the frontend making multiple API calls.

**Comment by benorourke** [comment]
https://feedback-analysis-grp-app-dev.herokuapp.com/dashboard?endpoint=feedback&endpoint=feedback_count

Changed the dashboard to follow conventions. The endpoints are optional.
