### ISSUE TITLE
Invalid Volume of Common Phrases

### ISSUE THREAD

**Issue by psyrr1** [GRP-17/feedback-backend#21]
Phrases are currently being counted twice when a new feedback item is created via the feedback component.

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR8: Invalid Volume of Common Phrases](https://trello.com/c/f5kwBgmY/53-spr8-invalid-volume-of-common-phrases)

**Comment by Hurstiii** [comment]
#31
