### ISSUE TITLE
Creating/Updating Dashboard Fails

### ISSUE THREAD

**Issue by Songkeys** [GRP-17/feedback-backend#25]
When creating a new dashboard, it says "internal server error". But then when I get all the dashboards again, I can actually see that this new dashboard is added indeed.

This happens with creating and updating.

**Comment by benorourke** [comment]
This has been fixed. The problem was that an expand() method was being called, with no values, where parameters were required.

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR10: Fix create/delete requests for Dashboards](https://trello.com/c/CSi4KvyN/92-spr10-fix-create-delete-requests-for-dashboards)
