### ISSUE TITLE
Code coverage >= 80%

### ISSUE THREAD

**Issue by Songkeys** [GRP-17/feedback-backend#28]
[![codecov](https://codecov.io/gh/GRP-17/feedback-backend/branch/development/graph/badge.svg)](https://codecov.io/gh/GRP-17/feedback-backend)

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR9: Reimplement Back-End Unit Tests](https://trello.com/c/YZQiElQ2/52-spr9-reimplement-back-end-unit-tests)
