### ISSUE TITLE
Use Jackson, don't parse JSON

### ISSUE THREAD

**Issue by Songkeys** [GRP-17/feedback-backend#4]
Helpful links:
<https://github.com/FasterXML/jackson>
<http://tutorials.jenkov.com/java-json/jackson-objectmapper.html>

**Comment by benorourke** [comment]
Until now, there was no need for Jackson as JPA serialised Feedback resources automatically.

However, now, with the sentiment count endpoint added - this is needed.

**Comment by benorourke** [comment]
Added Jackson serialisation.
