### ISSUE TITLE
Split Controller/Analysis Logic

### ISSUE THREAD

**Issue by Songkeys** [GRP-17/feedback-backend#6]
Split the controller logic and analysis logic. Business logic should be placed in classes called xxService.

**Comment by Songkeys** [comment]
I believe the concept of `Service` is to put all the business use cases into a separated `XxxService` class.

See:
- https://stackoverflow.com/questions/32731763/whats-the-best-practice-of-using-controller-service-and-repository-annotations
- https://stackoverflow.com/questions/14887871/creating-a-service-layer-for-my-mvc-application

Now we have a new service class `AnalysisService` in commit <https://github.com/GRP-17/feedback-backend/commit/38680a1c0875f15d1908b67f8d7422f31083c69b>. But I think it should be a `FeedbackService` instead, which includes all the feedback-related business services (like analysis & data storage). Just leave the responses logic to clients in `FeedbackController`.

**Comment by benorourke** [comment]
Renamed `AnalysisService` to `FeedbackService` and moved the (database) repository functionality to there. This should fix this issue.
